// <auto-generated />
using LoyaltyProgram.Api.Infrastructure.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LoyaltyProgram.Api.Migrations
{
    [DbContext(typeof(LoyaltyProgramContext))]
    [Migration("20180707190622_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoyaltyProgram.Api.Models.LoyaltyProgramSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Interests");

                    b.Property<int?>("LoyaltyProgramUserId");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProgramUserId");

                    b.ToTable("LoyaltyProgramSettings");
                });

            modelBuilder.Entity("LoyaltyProgram.Api.Models.LoyaltyProgramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LoyaltyPoints");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyProgramUser");
                });

            modelBuilder.Entity("LoyaltyProgram.Api.Models.LoyaltyProgramSettings", b =>
                {
                    b.HasOne("LoyaltyProgram.Api.Models.LoyaltyProgramUser", "LoyaltyProgramUser")
                        .WithMany("Settings")
                        .HasForeignKey("LoyaltyProgramUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
